import { ThemeConfig } from 'antd';

export const lightTheme: ThemeConfig = {
    components: {
        Table: {
            headerBg: '#ffffff'
        }
    },
    token: {
        colorTextBase: '#000',
        colorTextLightSolid: '#ffffff',
        colorBgBase: '#ffffff',
        fontFamily: 'IBM Plex Mono',
        fontSize: 14,
        lineWidth: 1,
        borderRadius: 8,
        sizeUnit: 4,
        sizePopupArrow: 16,
        controlHeight: 32,
        opacityImage: 1,
        sizeStep: 4,
        colorPrimary: '#0aa4b4',
        colorError: '#ff4d4f',
        colorWarning: '#faad14',
        colorSuccess: '#52c41a',
        colorInfo: '#1677ff',
        sizeXXL: 48,
        sizeXL: 32,
        sizeLG: 24,
        sizeMD: 20,
        sizeMS: 16,
        size: 16,
        sizeSM: 12,
        sizeXS: 8,
        sizeXXS: 4,
        controlHeightSM: 24,
        controlHeightXS: 16,
        controlHeightLG: 40,
        borderRadiusXS: 2,
        borderRadiusSM: 4,
        borderRadiusLG: 8,
        borderRadiusOuter: 4,
        colorText: 'rgba(0, 0, 0, 0.88)',
        colorTextSecondary: 'rgba(0, 0, 0, 0.65)',
        colorTextTertiary: 'rgba(0, 0, 0, 0.45)',
        colorTextQuaternary: 'rgba(0, 0, 0, 0.25)',
        colorFill: 'rgba(0, 0, 0, 0.15)',
        colorFillSecondary: 'rgba(0, 0, 0, 0.06)',
        colorFillTertiary: 'rgba(0, 0, 0, 0.04)',
        colorBgContainer: '#ffffff',
        colorFillQuaternary: 'rgba(0, 0, 0, 0.02)',
        colorBgLayout: '#f5f5f5',
        colorBgElevated: '#ffffff',
        colorBgSpotlight: 'rgba(0, 0, 0, 0.85)',
        colorBorder: 'rgba(0, 0, 0, 0.15)',
        colorBorderSecondary: 'rgba(0, 0, 0, 0.06)',
        colorSplit: 'rgba(0, 0, 0, 0.06)',
        colorPrimaryBg: '#dcf5f3',
        colorPrimaryBgHover: '#a2e8e6',
        colorPrimaryBorder: '#76dbdb',
        colorPrimaryBorderHover: '#4ecacf',
        colorPrimaryHover: '#2bb8c2',
        colorPrimaryActive: '#017c8f',
        colorPrimaryTextHover: '#005769',
        colorPrimaryText: '#003542',
        colorPrimaryTextActive: '#00161c',
        colorSuccessBg: '#f6ffed',
        colorSuccessBgHover: '#d9f7be',
        colorSuccessBorder: '#b7eb8f',
        colorSuccessBorderHover: '#95de64',
        colorSuccessHover: '#73d13d',
        colorSuccessActive: '#389e0d',
        colorSuccessTextHover: '#237804',
        colorSuccessText: '#135200',
        colorSuccessTextActive: '#092b00',
        colorWarningBg: '#fffbe6',
        colorWarningBgHover: '#fff1b8',
        colorWarningBorder: '#ffe58f',
        colorWarningBorderHover: '#ffd666',
        colorWarningHover: '#ffc53d',
        colorWarningActive: '#d48806',
        colorWarningTextHover: '#ad6800',
        colorWarningText: '#874d00',
        colorWarningTextActive: '#613400',
        colorErrorBg: '#fff1f0',
        colorErrorBgHover: '#ffccc7',
        colorErrorBorder: '#ffa39e',
        colorErrorBorderHover: '#ff7875',
        colorErrorHover: '#ff7875',
        colorErrorActive: '#cf1322',
        colorErrorTextHover: '#a8071a',
        colorErrorText: '#820014',
        colorErrorTextActive: '#5c0011',
        colorInfoBg: '#e6f4ff',
        colorInfoBgHover: '#bae0ff',
        colorInfoBorder: '#91caff',
        colorInfoBorderHover: '#69b1ff',
        colorInfoHover: '#4096ff',
        colorInfoActive: '#0958d9',
        colorInfoTextHover: '#003eb3',
        colorInfoText: '#002c8c',
        colorInfoTextActive: '#001d66',
        colorBorderBg: '#ffffff',
        colorLink: '#0aa4b4',
        colorLinkHover: '#2bb8c2',
        colorLinkActive: '#017c8f',
        colorHighlight: '#ff7875',
        controlOutline: '#dcf5f3',
        colorWarningOutline: '#fffbe6',
        colorErrorOutline: '#fff1f0',
        fontSizeSM: 12,
        fontSizeLG: 16,
        fontSizeXL: 20,
        fontSizeIcon: 12,
        fontSizeHeading1: 38,
        fontSizeHeading2: 30,
        fontSizeHeading3: 24,
        fontSizeHeading4: 20,
        fontSizeHeading5: 16,
        fontWeightStrong: 600,
        controlOutlineWidth: 2,
        controlItemBgActive: '#dcf5f3',
        controlItemBgActiveHover: '#a2e8e6',
        controlInteractiveSize: 16,
        opacityLoading: 0.65,
        padding: 16,
        paddingMD: 20,
        paddingSM: 12,
        paddingXS: 8,
        paddingXXS: 4,
        paddingLG: 24,
        paddingXL: 32,
        margin: 16,
        marginSM: 12,
        marginXS: 8,
        marginXXS: 4,
        marginLG: 24,
        marginXL: 48,
        controlPaddingHorizontal: 12,
        controlPaddingHorizontalSM: 8,
        paddingContentHorizontalLG: 24,
        paddingContentVerticalLG: 16,
        paddingContentHorizontal: 16,
        paddingContentVertical: 12,
        paddingContentHorizontalSM: 16,
        paddingContentVerticalSM: 8,
        boxShadow: '0 0 0 0 rgb(0, 0, 0)',
        boxShadowSecondary: '0 0 0 0 rgb(0, 0, 0)'
    }
};
